/*
 * (c) 2009.-2010. Ivan Voras <ivoras@fer.hr>
 * Released under the 2-clause BSDL.
 */


/*
 * PasswordDialog.java
 *
 * Created on 2010.01.17, 02:06:11
 */

package enotes;

import enotes.smartcard.CardCommunication;
import enotes.smartcard.CardMngr;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ivoras
 */
public class PasswordDialog extends javax.swing.JDialog {

    private String pwd = null;
    //static CardMngr cardManagerForApp = new CardMngr();
    static CardCommunication cardCommunicatorForApp = new CardCommunication();

    /** Creates new form PasswordDialog */
    public PasswordDialog() {
        initComponents();
        EnterPIN_jPasswordField.setText("");
        ConfirmPIN_jPasswordField.setText("");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        EnterPIN_jLabel = new javax.swing.JLabel();
        ConfirmPIN_jLabel = new javax.swing.JLabel();
        EnterPIN_jPasswordField = new javax.swing.JPasswordField();
        ConfirmPIN_jPasswordField = new javax.swing.JPasswordField();
        SendToCard_jButton = new javax.swing.JButton();

        setTitle("Enter password");
        setResizable(false);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        EnterPIN_jLabel.setText("Enter PIN");

        ConfirmPIN_jLabel.setText("Confirm PIN");

        EnterPIN_jPasswordField.setText("jPasswordField1");

        ConfirmPIN_jPasswordField.setText("jPasswordField2");

        SendToCard_jButton.setText("OK");
        SendToCard_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendToCard_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SendToCard_jButton)
                        .addGap(39, 39, 39)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EnterPIN_jLabel)
                            .addComponent(ConfirmPIN_jLabel))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConfirmPIN_jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EnterPIN_jPasswordField))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnterPIN_jLabel)
                    .addComponent(EnterPIN_jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmPIN_jLabel)
                    .addComponent(ConfirmPIN_jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(SendToCard_jButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void SendToCard_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendToCard_jButtonActionPerformed
        // TODO add your handling code here:
        
        String pin1 = new String(EnterPIN_jPasswordField.getPassword());
        String pin2 = new String(ConfirmPIN_jPasswordField.getPassword());
        if (!pin1.equals(pin2)) {
            JOptionPane.showMessageDialog(this, "The PINs do not match!");
            return;
        }
        
        char[] PIN_in_Array = EnterPIN_jPasswordField.getPassword();
         
        byte[] pin = new byte[PIN_in_Array.length];

	for (int m = 0; m < pin.length; m++) {
	  pin[m] = (byte) (PIN_in_Array[m] - 48);
          //System.out.printf("%s",pin[m]);
	 }
        CardCommunication.verifyPIN(pin);

        
        pwd = pin1;
        this.setVisible(false);

        
        
        
    }//GEN-LAST:event_SendToCard_jButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        pwd = null;
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConfirmPIN_jLabel;
    private javax.swing.JPasswordField ConfirmPIN_jPasswordField;
    private javax.swing.JLabel EnterPIN_jLabel;
    private javax.swing.JPasswordField EnterPIN_jPasswordField;
    private javax.swing.JButton SendToCard_jButton;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables


    public static String getPassword() {
        PasswordDialog pd = new PasswordDialog();
        pd.setResizable(false);
        pd.setModal(true);
        pd.setLocationRelativeTo(null);
        pd.setVisible(true);

        return pd.pwd;
    }
}
